In [28]:
import numpy as np
import time
import matplotlib.pyplot as plt

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


#### Case 1

In [3]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic =time.time()
c= np.dot(a,b)
toc =time.time()

print(c)
print('Vectorized version:' + str(1000*(toc-tic)) +'mc' )

c = 0
tic =time.time()
for i in range(1000000):
    c +=a[i]*b[i]
    
toc = time.time()
print(c)
print('For Loop version'+ str(1000*(toc-tic)) +'mc' )


250000.70950279862
Vectorized version:1.5289783477783203mc
250000.70950279236
For Loop version599.7509956359863mc


### Case 2

u = np.dot(A,v)
u =exp(v) ->   u = np.exp(v)
np.log(v)

### Vectorize logistic Regression

In [4]:
np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'

### Broadcasting

In [5]:
A = np.array([
    [56.0,0.0,4.4,68.4],
    [1.2,104.0,52.0,8.0],
    [1.8,135.0,99.0,0.9]
])
A

array([[ 56. ,   0. ,   4.4,  68.4],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [6]:
cal = A.sum(axis=1)
cal

array([128.8, 165.2, 236.7])

In [7]:
cal.reshape(1,3)

array([[128.8, 165.2, 236.7]])

In [8]:
cal.shape

(3,)

In [9]:
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  77.3])

In [10]:
100*A /cal

array([[94.91525424,  0.        ,  2.83140283, 88.48641656],
       [ 2.03389831, 43.51464435, 33.46203346, 10.34928849],
       [ 3.05084746, 56.48535565, 63.70656371,  1.16429495]])

In [11]:
np.array([1,2,3,4])+ 100

array([101, 102, 103, 104])

In [12]:
a =np.matrix([[1,2,3],[4,5,6]])
a

matrix([[1, 2, 3],
        [4, 5, 6]])

In [13]:
a + [100,200,300]

matrix([[101, 202, 303],
        [104, 205, 306]])

In [14]:
a + 100

matrix([[101, 102, 103],
        [104, 105, 106]])

#### Numpy Note

In [16]:
a = np.random.rand(5)
a

array([0.35577605, 0.14644726, 0.1816417 , 0.25544768, 0.46544234])

In [17]:
#rank 1
a.shape

(5,)

In [18]:
type(a)

numpy.ndarray

In [19]:
np.dot(a,a.T)

0.46290719446624545

In [20]:
a = np.random.rand(5,1)

In [21]:
a

array([[0.71371346],
       [0.7926035 ],
       [0.05831528],
       [0.27855026],
       [0.5964201 ]])

In [22]:
a.shape

(5, 1)

In [23]:
type(a)

numpy.ndarray

In [24]:
np.dot(a,a.T)

array([[0.5093869 , 0.56569179, 0.0416204 , 0.19880507, 0.42567305],
       [0.56569179, 0.62822031, 0.0462209 , 0.22077991, 0.47272466],
       [0.0416204 , 0.0462209 , 0.00340067, 0.01624374, 0.03478041],
       [0.19880507, 0.22077991, 0.01624374, 0.07759025, 0.16613297],
       [0.42567305, 0.47272466, 0.03478041, 0.16613297, 0.35571693]])

In [26]:
assert(a.shape ==(5,1))

In [27]:
assert(a.shape ==(1,5))

AssertionError: 

In [29]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a *b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [30]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a *b

In [31]:
c

array([[-0.2915595 , -0.27426732, -0.08675232],
       [ 0.24214168, -0.35190407, -0.21599409],
       [ 0.08615139,  0.04056496,  0.02310829]])

In [32]:
np.dot(a,b)

array([[-0.57069514],
       [-0.03214857],
       [-0.16545327]])